### ISSUE TITLE
BUG after installing the Middleware

### ISSUE THREAD

**Issue by creyD** [legion-an/django-models-logging#11]
Thanks for this project! I encountered this following bug after enabling the module and one of my testcases threw it. To be honest it is quite difficult to debug for me as it doesn't really show where it fails. I thought you might be able to assist here. Without the middleware it works, but the `request.user` isn't tracked.

```
Traceback (most recent call last):
File "c:\users\conrad\documents\github\api\app\.env\lib\site-packages\django\test\testcases.py", line 284, in _setup_and_call
    self._post_teardown()
  File "c:\users\conrad\documents\github\api\app\.env\lib\site-packages\django\test\testcases.py", line 1006, in _post_teardown
    self._fixture_teardown()
  File "c:\users\conrad\documents\github\api\app\.env\lib\site-packages\django\test\testcases.py", line 1248, in _fixture_teardown
    connections[db_name].check_constraints()
  File "c:\users\conrad\documents\github\api\app\.env\lib\site-packages\django\db\backends\sqlite3\base.py", line 353, in check_constraints
    raise IntegrityError(
django.db.utils.IntegrityError: The row in table 'models_logging_change' with primary key '1' has an invalid foreign key: models_logging_change.user_id contains a value '10' that does not have a corresponding value in user_user.id.
```

**Comment by creyD** [comment]
This is actually fixed with #13
